# Copyright (c) 2022 Nitro Agility S.r.l.
# SPDX-License-Identifier: Apache-2.0

name: Publish to NuGet

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: read

env:
  PROJECT_PATH: ./Permguard/Permguard.csproj
  PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}/output
  NUGET_SOURCE_URL: https://api.nuget.org/v3/index.json

jobs:
  publish:
    name: Test, pack, and publish
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Extract version from tag
        shell: bash
        run: echo "PACKAGE_VERSION=${GITHUB_REF#refs/tags/v}" >> "$GITHUB_ENV"

      - name: Restore
        run: dotnet restore SamplePermguard.sln
      - name: Test
        run: dotnet test SamplePermguard.sln --no-restore --configuration Release -m:1
      - name: Pack
        run: >-
          dotnet pack ${{ env.PROJECT_PATH }}
          -p:PackageVersion=${{ env.PACKAGE_VERSION }}
          --no-restore --configuration Release
          --output ${{ env.PACKAGE_OUTPUT_DIRECTORY }}
      - name: Push package
        run: >-
          dotnet nuget push
          "${{ env.PACKAGE_OUTPUT_DIRECTORY }}/Permguard.${{ env.PACKAGE_VERSION }}.nupkg"
          --source "${{ env.NUGET_SOURCE_URL }}"
          --api-key "${{ secrets.NUGET_AUTH_TOKEN }}"
          --skip-duplicate
